language: python
matrix:
  include:
    - python: '3.6'
      os: linux
    - python: '3.7'
      os: linux

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda install -q requests python=$TRAVIS_PYTHON_VERSION pyflakes flake8 mock six psutil pytest-cov pytest-mock pytest-xdist "networkx>2" git conda-build
  - pip install --no-deps .
  - conda info -a

script:
  - flake8 .
  # tests utilize automated git repo creation and commits.  Need to set this up.
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - $HOME/miniconda/bin/py.test -v --cov conda_concourse_ci --cov-report xml tests -n 4 -m "not serial"
  - $HOME/miniconda/bin/py.test -v --cov conda_concourse_ci --cov-report xml --cov-append tests -m "serial"
  - flake8

git:
  depth: 10000

sudo: false

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
